# Generated by Django 4.2.5 on 2024-05-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FfwcLastUpdateDateExperimental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_date', models.DateField(unique=True)),
                ('entry_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'ffwc_last_update_date_experimental',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='waterlevelobservations',
            options={'get_latest_by': 'wl_date', 'managed': False, 'verbose_name': 'Observed Waterlevel', 'verbose_name_plural': 'Observed Waterlevels'},
        ),
    ]
