# Generated by Django 4.2.5 on 2024-05-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0002_ffwclastupdatedateexperimental_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLevelForecastsExperimentals',
            fields=[
                ('fc_id', models.AutoField(primary_key=True, serialize=False)),
                ('st_id', models.IntegerField()),
                ('fc_date', models.DateTimeField()),
                ('waterlevel_min', models.DecimalField(db_column='waterLevel_min', decimal_places=2, max_digits=10)),
                ('waterlevel_max', models.DecimalField(db_column='waterLevel_max', decimal_places=2, max_digits=10)),
                ('waterlevel_mean', models.DecimalField(db_column='waterLevel_mean', decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Waterlevel_forecast_experimentals(Forecast)',
                'verbose_name_plural': 'Waterlevel Forecast Experimentals(Forecasts)',
                'db_table': 'water_level_forecast_experimentals',
                'managed': False,
            },
        ),
    ]
