# Generated by Django 4.2.5 on 2024-08-01 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0003_waterlevelforecastsexperimentals'),
    ]

    operations = [
        migrations.CreateModel(
            name='FfwcStationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.CharField(blank=True, db_column='St ID', max_length=8, null=True)),
                ('station', models.CharField(blank=True, db_column='Station', max_length=26, null=True)),
                ('river', models.CharField(blank=True, db_column='River', max_length=22, null=True)),
                ('dl_mmsl_field', models.CharField(blank=True, db_column='DL (mMSL)', max_length=9, null=True)),
                ('pmdl_mmsl_field', models.CharField(blank=True, db_column='PMDL (mMSL)', max_length=13, null=True)),
                ('rhwl_mmsl_mpwd_0_46_field', models.CharField(blank=True, db_column='RHWL mMSL(mPWD -0.46)', max_length=21, null=True)),
                ('rhwl_mpwd_confirmed', models.CharField(blank=True, db_column='RHWL (mPWD) Confirmed', max_length=21, null=True)),
                ('date_of_rhwl', models.CharField(blank=True, db_column='Date of RHWL', max_length=12, null=True)),
                ('gauge_shift_pwd_msl_field', models.CharField(blank=True, db_column='Gauge Shift (PWD-MSL)', max_length=21, null=True)),
                ('effective_date', models.CharField(blank=True, db_column='Effective Date', max_length=14, null=True)),
                ('latitude', models.CharField(blank=True, db_column='Latitude', max_length=8, null=True)),
                ('longitude', models.CharField(blank=True, db_column='Longitude', max_length=9, null=True)),
                ('basin', models.CharField(blank=True, db_column='Basin', max_length=11, null=True)),
                ('h_division', models.CharField(blank=True, db_column='H.Division', max_length=10, null=True)),
                ('division', models.CharField(blank=True, db_column='Division', max_length=10, null=True)),
                ('district', models.CharField(blank=True, db_column='District', max_length=16, null=True)),
                ('upazilla', models.CharField(blank=True, db_column='Upazilla', max_length=18, null=True)),
                ('union', models.CharField(blank=True, db_column='Union', max_length=28, null=True)),
                ('forecast_status', models.CharField(blank=True, db_column='Forecast Status', max_length=15, null=True)),
                ('rimes_medium_range', models.CharField(blank=True, db_column='RIMES Medium Range', max_length=18, null=True)),
                ('model_boundary', models.CharField(blank=True, db_column='Model Boundary', max_length=14, null=True)),
                ('pre_monsoon', models.CharField(blank=True, db_column='Pre-Monsoon', max_length=11, null=True)),
                ('dry', models.CharField(blank=True, db_column='Dry', max_length=3, null=True)),
                ('sms_solution_id', models.CharField(blank=True, db_column='SMS Solution ID', max_length=15, null=True)),
                ('fw_data_location', models.CharField(blank=True, db_column='FW Data Location', max_length=16, null=True)),
                ('web_id', models.CharField(blank=True, db_column='Web-ID', max_length=6, null=True)),
                ('ffdata_header', models.CharField(blank=True, db_column='ffData Header', max_length=23, null=True)),
            ],
            options={
                'db_table': 'ffwc_station_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForecastWithStationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('stationName', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='name', related_query_name='name', to='data_load.waterlevelforecasts')),
            ],
        ),
    ]
