# Generated by Django 4.2.5 on 2024-09-01 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0004_ffwcstationinfo_forecastwithstationdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ffwcrainfallstations',
            options={'managed': False},
        ),
    ]
