# Generated by Django 4.2.5 on 2024-09-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0006_alter_ffwcrainfallstations_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndianWaterLevelObservations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('station_id', models.IntegerField()),
                ('station_code', models.CharField(max_length=200)),
                ('data_time', models.DateTimeField()),
                ('waterlevel', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'indian_water_level_observations',
                'managed': False,
            },
        ),
    ]
